Repository DIT113-V22/group-12, pull requests merged in 2022-04, with the labels that each got.

#20 Layout design for payment and item review/quantity
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/CustomerItemVerify.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/CustomerPayment.java
  CarEshipApp/app/src/main/res/drawable/background_gardient.xml
  CarEshipApp/app/src/main/res/drawable/backslash.xml
  CarEshipApp/app/src/main/res/drawable/custom_input.xml
  CarEshipApp/app/src/main/res/drawable/pills.png
  CarEshipApp/app/src/main/res/drawable/visa_y_mastercard_mastercard_number_symbol_text_logo_transparent_png_372974.png
  CarEshipApp/app/src/main/res/layout/customer_item_verify.xml
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/values/ids.xml
  CarEshipApp/app/src/main/res/values/strings.xml
  CarEshipApp/local.properties
Labels: Sprint #1

#22 Fixed bug: credentials are not inserted
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/DBHelperClass.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityCreateAccount.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityLoginPage.java
Labels: Sprint #1, Bug fix

#26 Multi login screen, staff login layout
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/StaffLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/UserActivityController.java
  CarEshipApp/app/src/main/res/drawable/background_gardient.xml
  CarEshipApp/app/src/main/res/drawable/pngwing_com__4_.png
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
  CarEshipApp/app/src/main/res/layout/user_activity_controller.xml
Labels: Sprint #1

#30 Add Layout design for medicines
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/CommonCold.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/allergies.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/anxiety.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/asthma.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/heartdisease.java
  CarEshipApp/app/src/main/res/drawable-v24/danilo_alvesd_a7odg45prsm_unsplash.jpg
  CarEshipApp/app/src/main/res/layout/allergies.xml
  CarEshipApp/app/src/main/res/layout/anxiety.xml
  CarEshipApp/app/src/main/res/layout/asthma.xml
  CarEshipApp/app/src/main/res/layout/commoncold.xml
  CarEshipApp/app/src/main/res/layout/heartdisease.xml
  CarEshipApp/local.properties
Labels: Sprint #1

#37 Updated UI design
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/CustomerAddress.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/StaffLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/UpdatePassword.java
  CarEshipApp/app/src/main/res/drawable-v24/danilo_alvesd_a7odg45prsm_unsplash.jpg
  CarEshipApp/app/src/main/res/drawable/background.jpg
  CarEshipApp/app/src/main/res/drawable/background2.jpg
  CarEshipApp/app/src/main/res/drawable/background_gardient.xml
  CarEshipApp/app/src/main/res/drawable/backslash.xml
  CarEshipApp/app/src/main/res/drawable/bonbon_phone_with_online_medicine_service_pills_and_stethoscope_1.png
  CarEshipApp/app/src/main/res/drawable/button.xml
  CarEshipApp/app/src/main/res/drawable/collecting_medicines.png
  CarEshipApp/app/src/main/res/drawable/confirmation__1_.png
  CarEshipApp/app/src/main/res/drawable/delivery.png
  CarEshipApp/app/src/main/res/drawable/delivery__1_.png
  CarEshipApp/app/src/main/res/drawable/design_of_online_payment.png
  CarEshipApp/app/src/main/res/drawable/gummy_location.png
  CarEshipApp/app/src/main/res/drawable/ic_baseline_search_24.xml
  CarEshipApp/app/src/main/res/drawable/kindpng_4854845.png
  CarEshipApp/app/src/main/res/drawable/login_illustration.png
  CarEshipApp/app/src/main/res/drawable/medicine.png
  CarEshipApp/app/src/main/res/drawable/medicine_delivery.png
  CarEshipApp/app/src/main/res/drawable/office_workplace.png
  CarEshipApp/app/src/main/res/drawable/payment.png
  CarEshipApp/app/src/main/res/drawable/pngwing_com__4_.png
  CarEshipApp/app/src/main/res/drawable/say_hello_to_new_people.png
  CarEshipApp/app/src/main/res/drawable/sign_up_form.png
  CarEshipApp/app/src/main/res/drawable/visa_y_mastercard.png
  CarEshipApp/app/src/main/res/layout/activity_main_category_list.xml
  CarEshipApp/app/src/main/res/layout/activity_main_create_account.xml
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/allergies.xml
  CarEshipApp/app/src/main/res/layout/anxiety.xml
  CarEshipApp/app/src/main/res/layout/asthma.xml
  CarEshipApp/app/src/main/res/layout/commoncold.xml
  CarEshipApp/app/src/main/res/layout/customer_address.xml
  CarEshipApp/app/src/main/res/layout/customer_item_verify.xml
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/layout/heartdisease.xml
  CarEshipApp/app/src/main/res/layout/order_confirmation.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
  CarEshipApp/app/src/main/res/layout/track_order.xml
  CarEshipApp/app/src/main/res/layout/user_activity_controller.xml
  CarEshipApp/app/src/main/res/values-night/themes.xml
  CarEshipApp/app/src/main/res/values/colors.xml
  CarEshipApp/app/src/main/res/values/strings.xml
  CarEshipApp/app/src/main/res/values/themes.xml
  CarEshipApp/local.properties
Labels: Sprint #2, Improvement

#41 Changed logo's position and added reset password layout
  CarEshipApp/app/src/main/java/com/example/careshipapp/UpdatePassword.java
  CarEshipApp/app/src/main/res/drawable/medical_checkup.png
  CarEshipApp/app/src/main/res/drawable/vecteezy_safer_internet_day_.jpg
  CarEshipApp/app/src/main/res/drawable/wavy_med_06_single_05.jpg
  CarEshipApp/app/src/main/res/layout/activity_main_category_list.xml
  CarEshipApp/app/src/main/res/layout/activity_main_create_account.xml
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/customer_address.xml
  CarEshipApp/app/src/main/res/layout/customer_item_verify.xml
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/layout/order_confirmation.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
  CarEshipApp/app/src/main/res/layout/track_order.xml
  CarEshipApp/app/src/main/res/layout/update_password.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Sprint #2, Improvement

#45 Grouped classes in packages
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/UpdatePassword.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickFunctionality.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/MqttClient.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CommonCold.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerAddress.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerItemVerify.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerPayment.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/MainActivityCategoryList.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/OrderConfirmation.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/TrackOrder.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/UpdatePassword.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/allergies.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/anxiety.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/asthma.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/heartdisease.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/DBHelperClass.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityCreateAccount.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/StaffLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/UserActivityController.java
  CarEshipApp/app/src/main/res/layout/activity_main_category_list.xml
  CarEshipApp/app/src/main/res/layout/activity_main_create_account.xml
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/allergies.xml
  CarEshipApp/app/src/main/res/layout/anxiety.xml
  CarEshipApp/app/src/main/res/layout/asthma.xml
  CarEshipApp/app/src/main/res/layout/commoncold.xml
  CarEshipApp/app/src/main/res/layout/heartdisease.xml
  CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
Labels: Sprint #2, Code Design Fix
