Repository DIT113-V22/group-12, pull requests merged in 2022-05, with the labels that each got.

#49 Updated Arduino CI workflow with MQTT library
  .github/workflows/arduino-build.yml
Labels: enhancement

#52 Android .gitignore file
  CarEshipApp/.gitignore
  CarEshipApp/local.properties
Labels: Sprint #2, Workflow Enhancement

#57 Customer address, update password(unfinished)
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerAddress.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/UpdatePassword.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/DBHelperClass.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityCreateAccount.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/StaffLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/UpdatePassword.java
  CarEshipApp/app/src/main/res/layout/activity_main_create_account.xml
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/customer_address.xml
  CarEshipApp/app/src/main/res/layout/update_password.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Sprint #2

#60 Android-side MQTT implementation
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickFunctionality.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
  CarEshipApp/build.gradle
  CarEshipApp/gradle.properties
Labels: Sprint #2, Feature

#61 Estimated time of delivery
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/OrderConfirmation.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/TrackOrder.java
  CarEshipApp/app/src/main/res/layout/track_order.xml
Labels: Sprint #2

#64 Add application icon
  CarEshipApp/app/src/main/ic_launcher-playstore.png
  CarEshipApp/app/src/main/res/drawable/ic_launcher_background.xml
  CarEshipApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  CarEshipApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  CarEshipApp/app/src/main/res/mipmap-hdpi/ic_launcher.png
  CarEshipApp/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  CarEshipApp/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  CarEshipApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  CarEshipApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  CarEshipApp/app/src/main/res/mipmap-mdpi/ic_launcher.png
  CarEshipApp/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  CarEshipApp/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  CarEshipApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  CarEshipApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  CarEshipApp/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  CarEshipApp/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  CarEshipApp/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  CarEshipApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  CarEshipApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  CarEshipApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  CarEshipApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  CarEshipApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  CarEshipApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  CarEshipApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  CarEshipApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  CarEshipApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  CarEshipApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  CarEshipApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  CarEshipApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  CarEshipApp/app/src/main/res/values/ic_launcher_background.xml
Labels: Sprint #2

#67 Add order list
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/ListOrders.java
  CarEshipApp/app/src/main/res/layout/activity_list_orders.xml
Labels: Sprint #2

#68 Android CI update with google secret access job.
  .github/workflows/android.yml
Labels: Improvement, Workflow Enhancement

#71 layout for categorising carEship products
  CarEshipApp/app/src/main/res/drawable-v24/backgorund_shop.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_add_circle_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_arrow_back_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_favorite_border_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_menu_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_remove_circle_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/ic_baseline_shopping_cart_24.xml
  CarEshipApp/app/src/main/res/drawable-v24/vitamins.png
  CarEshipApp/app/src/main/res/layout/activity_category_medicine.xml
  CarEshipApp/app/src/main/res/layout/activity_shop.xml
  CarEshipApp/app/src/main/res/layout/activity_shop_detail.xml
  CarEshipApp/app/src/main/res/layout/item_product.xml
  CarEshipApp/app/src/main/res/layout/order_item.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Sprint #3

#72 Update README.md
  README.md
Labels: documentation

#77 Camera implementation Arduino
  arduino/smartcar/smartcar.ino
Labels: Feature, Sprint #3

#74 Fix firebase configuration error in CI
  .github/workflows/android.yml
  CarEshipApp/app/build.gradle
Labels: bug, help wanted

#79 Android-side camera implementation
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
  CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Sprint #3

#80 Register Customer using firebase
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityCreateAccount.java
  CarEshipApp/app/src/main/res/drawable/gummy_location.png
  CarEshipApp/app/src/main/res/layout/activity_main_create_account.xml
  CarEshipApp/app/src/main/res/values/strings.xml
  CarEshipApp/build.gradle
  CarEshipApp/gradle/wrapper/gradle-wrapper.properties
Labels: Medium, Sprint #3

#83 Customer payment using credit card and email verification
  .DS_Store
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerPayment.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/EmailVerification.java
  CarEshipApp/app/src/main/res/drawable/nicepng_email_symbol_png_9602830.png
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/layout/email_verification.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Medium, Sprint #3

#85 Updated firebase customer, staff login(with access restrictions)
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/CustomerPayment.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/CustomerLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityCreateAccount.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/MainActivityLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/StaffLoginPage.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/User.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/UserActivityController.java
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/forgot_password_auth.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
Labels: Medium, Sprint #3

#86 Back, left, and right InfraRed sensors
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/DBHelperClass.java
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#92 Add Introduction slider
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/OnBoardingActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/user_management/SliderAdapter.java
  CarEshipApp/app/src/main/res/drawable/onboardscreen1.jpg
  CarEshipApp/app/src/main/res/drawable/onboardscreen2.jpg
  CarEshipApp/app/src/main/res/drawable/onboardscreen3.jpg
  CarEshipApp/app/src/main/res/font/allerta.xml
  CarEshipApp/app/src/main/res/font/hammersmith_one.xml
  CarEshipApp/app/src/main/res/layout/activity_on_boarding.xml
  CarEshipApp/app/src/main/res/layout/sliding_layout.xml
  CarEshipApp/app/src/main/res/values/colors.xml
  CarEshipApp/app/src/main/res/values/font_certs.xml
  CarEshipApp/app/src/main/res/values/preloaded_fonts.xml
  CarEshipApp/app/src/main/res/values/strings.xml
  CarEshipApp/settings.gradle
Labels: Low, Sprint #3

#94 Implementation of acceleration and deceleration of the car.
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickFunctionality.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
Labels: Sprint #3

#97 Implementation of autopilot toggle switch button.
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
  CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml
  CarEshipApp/app/src/main/res/values/ids.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Sprint #3

#98 Adding mod
  careship-mod/mod
Labels: Sprint #3

#100 Adding the search filter
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/ShowAllActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/adapters/ShowAllAdapter.java
  CarEshipApp/app/src/main/res/layout/activity_show_all.xml
  CarEshipApp/build.gradle
Labels: Low, Sprint #3

#102 CarEship mod files
  careship-mod/LICENSE
  careship-mod/Material #100.material
  careship-mod/Material #101.material
  careship-mod/Material #102.material
  careship-mod/Material #103.material
  careship-mod/Material #15.material
  careship-mod/Material #16.material
  careship-mod/Material #18.material
  careship-mod/Material #19.material
  careship-mod/Material #2.material
  careship-mod/Material #20.material
  careship-mod/Material #87.material
  careship-mod/Material #88.material
  careship-mod/Material #93.material
  careship-mod/Material #94.material
  careship-mod/Material #97.material
  careship-mod/Material #98.material
  careship-mod/README.md
  careship-mod/VERSION.md
  careship-mod/default_env.tres
  careship-mod/export_presets.cfg
  careship-mod/icon.png
  careship-mod/icon.png.import
  careship-mod/project.godot
  careship-mod/roof.material
Labels: Sprint #3

#105 Delete LICENSE
  careship-mod/LICENSE
Labels: Sprint #3

#108 Updated_Customer_payment
  .DS_Store
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CheckoutActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CustomerPaymentActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/DetailedActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/EmailVerificationActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/PaymentActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/PaymentConfirmationActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/TrackOrderActivity.java
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/layout/email_verification.xml
  CarEshipApp/app/src/main/res/layout/order_confirmation.xml
  CarEshipApp/app/src/main/res/layout/track_order.xml
  CarEshipApp/app/src/main/res/layout/update_password.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Improvement, Sprint #3

#109 Autopilot driving Arduino implementation
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#110 Adding Retrospective 1 and 2
  README.md
Labels: Sprint #3

#112 added badges
  README.md
Labels: Sprint #3

#116 Add StaffOrder Activity
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/AndroidManifest.xml
  CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/AddressActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CheckoutActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CustomerPaymentActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/DetailedActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/PaymentActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/StaffLoginActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/StaffOrderActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/adapters/StaffOrderAdapter.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/models/StaffOrderModel.java
  CarEshipApp/app/src/main/res/drawable/background_gardient.xml
  CarEshipApp/app/src/main/res/drawable/calling.png
  CarEshipApp/app/src/main/res/drawable/map.png
  CarEshipApp/app/src/main/res/drawable/mapcare.jpg
  CarEshipApp/app/src/main/res/drawable/phone_call.png
  CarEshipApp/app/src/main/res/drawable/viber.png
  CarEshipApp/app/src/main/res/layout/activity_address.xml
  CarEshipApp/app/src/main/res/layout/activity_payment.xml
  CarEshipApp/app/src/main/res/layout/activity_staff_order.xml
  CarEshipApp/app/src/main/res/layout/customer_payment.xml
  CarEshipApp/app/src/main/res/layout/email_verification.xml
  CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml
  CarEshipApp/app/src/main/res/layout/map_layout.xml
  CarEshipApp/app/src/main/res/layout/order_confirmation.xml
  CarEshipApp/app/src/main/res/layout/staff_order_item.xml
  CarEshipApp/app/src/main/res/layout/user_activity_controller.xml
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Medium, Sprint #3

#126 Added an updated problem description
  README.md
Labels: documentation, Sprint #4

#127 added sprint 3 demo to readme
  README.md
Labels: documentation, Sprint #4

#128 Changed demos display
  README.md
Labels: documentation, Sprint #4

#130 sprint demo videos gifs bug solve attempt
  README.md
Labels: bug, documentation, Sprint #4

#131 Added links to demo sprints video to README.md
  README.md
Labels: documentation, Sprint #4

#132 Update README.md
  README.md
Labels: documentation, Sprint #4

#133 Left and right sensors obstacle avoidance implementation.
  arduino/smartcar/smartcar.ino
Labels: Sprint #4

#136 Board and vehicle sensor configuration files
  arduino/smartcar/board_config.json
  arduino/smartcar/vehicle_config.json
Labels: Sprint #4

#139 Android CI update for tests
  .github/workflows/android.yml
Labels: Sprint #4

#145 Enabled password show/hide in login screens
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CustomerPaymentActivity.java
  CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml
  CarEshipApp/app/src/main/res/layout/order_confirmation.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
Labels: Improvement, Sprint #4

#146 Updating Readme file
  README.md
Labels: documentation, Improvement, Sprint #4

#147 fix bug and code enhancements
  .DS_Store
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/AddressActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/ForgotPasswordAuthActivity.java
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/StaffLoginActivity.java
  CarEshipApp/app/src/main/res/layout/activity_address.xml
  CarEshipApp/app/src/main/res/layout/staff_login_page.xml
  arduino/.DS_Store
Labels: enhancement, Bug fix, Sprint #4

#148 description for welcome pages
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/main/java/com/example/careshipapp/gui/adapters/SliderAdapter.java
  CarEshipApp/app/src/main/res/values/strings.xml
Labels: Low, Sprint #4

#149 Update android.yml
  .github/workflows/android.yml
Labels: Sprint #4

#141 Instrumented UI tests for different activity views and layouts.
  CarEshipApp/app/build.gradle
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/AddressActivityTest.java
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/CreateAccountActivityTest.java
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/CustomerPaymentActivityTest.java
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/ExampleInstrumentedTest.java
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/JoystickMainActivityTest.java
  CarEshipApp/app/src/androidTest/java/com/example/careshipapp/StaffLoginActivityTest.java
Labels: Sprint #4

#151 Update README.md
  README.md
Labels: documentation

#152 Update README.md
  README.md
Labels: documentation, Sprint #4

#153 Final Android CI update
  .github/workflows/android.yml
Labels: Refactor, Sprint #4
